apiVersion: apps/v1
kind: Deployment
metadata:
  name: pizza-fusion-menu
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pizza-fusion-menu
  template:
    metadata:
      labels:
        app: pizza-fusion-menu
    spec:
      containers:
      - name: pizza-fusion-menu
        image: docker.io/docker380431/pizza-fusion-menu-msc:latest
        ports:
        - containerPort: 3002
        envFrom:
        - configMapRef:
            name: pizza-fusion-config