apiVersion: v1
kind: Service
metadata:
  name: pizza-fusion-menu-service
spec:
  selector:
    app: pizza-fusion-menu
  ports:
    - protocol: TCP
      port: 3002
      targetPort: 3002
  type: ClusterIP